# Generated by Django 2.1 on 2018-08-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitaion',
            name='message',
            field=models.CharField(help_text="It's always nice to add a friendly message", max_length=300, verbose_name='Optional Message'),
        ),
        migrations.AlterField(
            model_name='invitaion',
            name='to_user',
            field=models.ForeignKey(help_text='please select a user you eant to play with', on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
    ]
